### ISSUE TITLE
No friends when offline

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-security-friends#10]
When loading a wiki on a disconnected device, the friends security plugin will not let me pass into my own wiki. This is due to a missing lock. Also see the conversation from below https://github.com/fedwiki/wiki-security-friends/issues/8#issuecomment-355372504

![bildschirmfoto von 2019-02-11 18-01-02](https://user-images.githubusercontent.com/1645308/52579994-aba79680-2e27-11e9-8ded-c47be2262e4e.png)

Graciously, `wiki` still allows me to edit in local storage.
This is eventually caused by an asset from a foreign domain, which is not provided by the offline host.

![bildschirmfoto von 2019-02-11 18-04-05](https://user-images.githubusercontent.com/1645308/52580038-c1b55700-2e27-11e9-9716-72735c8313ee.png)

Apparently this is actually an upstream issue, and should actually live with the `wiki-client`?

**Comment by WardCunningham** [comment]
Help me understand what steps will repeat this issue.

**Comment by almereyda** [comment]
This happens in offline scenarios, when wiki-client cannot retrieve public assets needed to display the lock icon.

---

1. Create a wiki in a LAN
2. Secure it with friends to have basic access control
3. Disconnect the LAN from the Internet
4. Open a wiki in the LAN

---

The lock icon will not be displayed.

**Comment by WardCunningham** [comment]
Maybe critical icons like the lock can be built into the ui with data urls rather than fetching them.

**Comment by paul90** [comment]
Thanks for raising this. There are a number of plugins that also make use of public assets, this is something that I looked at when creating the dat variant, so identifying the plugins that will also need some work in such an environment.

**Comment by paul90** [comment]
Fixed by + wiki-security-friends@0.2.1
