### ISSUE TITLE
Writing to an unclaimed wiki is forbidden

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-security-friends#11]
Once wikis were publically writable when being unclaimed. This is not working anymore.

![bildschirmfoto von 2019-02-11 18-12-35](https://user-images.githubusercontent.com/1645308/52580495-c62e3f80-2e28-11e9-8510-50b9ffbe376e.png)

Would this rather be a more general concern for the `wiki-server`, or could we allow this on a per-security-plugin basis, eventually with another command line flag?

**Comment by WardCunningham** [comment]
I don't know that we are always consistent. I have found the `--security_legacy` command line flag useful. Here is a reminder that I keep for myself when editing a plugin's about pages.

http://plugins.fed.wiki.org/plugin-documentation.html

**Comment by almereyda** [comment]
Thank you, 8bb4557bc5cc3584dc62026da9f1bd81b7ae016e was unknown to me until now. Would it seem feasible to close here and add a little mention about the rationale for that commit to https://github.com/fedwiki/wiki/blob/master/security.md?
