### ISSUE TITLE
describe use cases and workflows for friendly security.

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki-security-friends#8]
This security plugin parallels wiki-security-persona which is itself configurable as is the client and server support within wiki for pluggable identity systems. How is anyone, even a skilled administrator, to figure out what can be done with this on their own?

**Comment by bashrc** [comment]
So if there's an owner.json file, what is its structure and what directory is it located in?

**Comment by paul90** [comment]
The owner.json file is placed in the status directory for the wiki site, this will be in the `.wiki` directory of the user that starts wiki, unless configured otherwise.

**Comment by bashrc** [comment]
I'm still not really any the wiser as to how a user is supposed to authenticate. If it's only designed to work with proprietary identity systems then I might just give up.

**Comment by paul90** [comment]
The format owner.json is:

```
{
  "name": "nick",
  "friend": {
    "secret": "secret"
  }
}
```
were `nick` should be the display name of the wiki owner (initially a random 6 character string), and  `secret` a generated shared secret used by the owner to identify themself.

**Comment by bashrc** [comment]
What about on the client side. How do they authenticate with the secret?

**Comment by paul90** [comment]
There is a padlock in the page footer.
![screenshot-2018-1-4 welcome visitors](https://user-images.githubusercontent.com/1552489/34578212-0278f8da-f17c-11e7-9d93-ad63b62fc500.png)
If the site has not been claimed clicking on the padlock will claim the site, if already claimed it will give a dialog to enter the secret.

**Comment by bashrc** [comment]
I don't see the lock symbol though. Does this depend upon googleapi, because I remove or block any links to Google.

Also does owner.json need to exist both on the server and client?

Note: this seems like a really cumbersome way to authenticate. Some kind of simple auth would be much easier.

**Comment by paul90** [comment]
Nothing google related - the lock symbol is from font awesome webfont. Maybe you are blocking that!

`owner.json` is only on the server - a cookie gets saved in the browser to persist the session.

**Comment by bashrc** [comment]
It was font-awesome. I installed the debian package for that, added an alias in the web config and changed the bootstrapcdn url to the local site. That worked.
